### ISSUE TITLE
running marker_profiling_example

### ISSUE THREAD

**Issue by AlexBouz** [hammerlab/cytokit#11]
Greetings and thank you for sharing this fantastic tool, i'm running the example script and got stuck at the last processing step, any comment is appreciated!
![Untitled](https://user-images.githubusercontent.com/37419030/65096184-13abf580-d992-11e9-8c44-a5acaa3f87cd.png)

**Comment by eric-czech** [comment]
Hi @AlexBouz , the configuration for that example project assumes there are at least 2 gpus present.  I changed it to avoid this in the future, but as a workaround you can update the **processor.args.gpus** argument (set it to "gpus: [0]") in the experiment_pha.yaml file at ```cytokit/pub/config/cellular-marker``` and run the notebook again (from the start).  Alternatively, you could update the cell that creates the configurations to do this for you:

cytokit config editor --base-config-path=/lab/repos/cytokit/pub/config/cellular-marker/experiment_pha.yaml --output-dir=$1 \
set name 'Cellular Marker Example' \
set acquisition.region_height 1 \
set acquisition.region_width 1 \
set acquisition.num_z_planes 7 \
set environment.index_symlinks '{z:{1:14,2:15,3:16,4:17,5:18,6:19,7:20}}' \
**set processor.args.gpus '[0]'** \
save_variant v00/config \
exit

**Comment by AlexBouz** [comment]
Hi Eric, thank you for your help, i went for the workaround for ease of use by adding the set processor.args.gpus '[0]' to the cell, the full script was run,
![UI cytokit](https://user-images.githubusercontent.com/37419030/65175836-a5af0f00-da21-11e9-8369-b30f32423c64.png)
![UI cytokit backlog](https://user-images.githubusercontent.com/37419030/65175842-a6e03c00-da21-11e9-830d-98f206de35eb.png)

 for the run explorer UI, it opened as expected! 
![Configuration file created](https://user-images.githubusercontent.com/37419030/65174859-b65e8580-da1f-11e9-8c8e-de370dd10359.png)
![Configuration arguments loaded](https://user-images.githubusercontent.com/37419030/65174865-b9f20c80-da1f-11e9-8121-1bba64381235.png)
![Cytokit UI](https://user-images.githubusercontent.com/37419030/65174874-bcecfd00-da1f-11e9-8b48-60652d7c906d.png)

I'm still getting familiar with your tool and hope to test it with my own images in ome multitiff format

**Comment by AlexBouz** [comment]
Hi Eric, sorry to bother again, but i'm looking for the codex mouse spleen  notebooks available to test with cytokit (cy5_montage, file_eda, and segmentation_debug), the linkhttp://welikesharingdata.blob.core.windows.net/forshare/index.html has lot of files and it's hard to tell which input was used, any guidance is appreciated!

**Comment by eric-czech** [comment]
Hey @AlexBouz , glad that example worked for you.  The files I had used are all under the "Deconvolved Z-stacks" section with the subheading
