### ISSUE TITLE
Imaging mass cytometry

### ISSUE THREAD

**Issue by mkeays** [hammerlab/cytokit#13]
Hello,

I am looking for open source, automation-friendly software to do end-to-end processing for imaging mass cytometry data, and I was wondering if Cytokit would fit the bill? I have data similar to the example dataset [here](https://github.com/BodenmillerGroup/histoCAT/releases/download/histoCAT_1.76/Example_Images.zip).

Thanks,
Maria

**Comment by eric-czech** [comment]
Hi Maria,

I don't believe any IMC images were used to train the CellProfiler nuclei detection U-Net that Cytokit uses so it's probably not a great idea, or at least it would be hard to justify applying it without validating the model for that imaging modality first.

Out of curiosity though I ran it on one of your H3 images and the results are better than I thought, but still not as good as fluorescent images (w.r.t. nuclei detection):

![Screen Shot 2019-11-06 at 5 12 25 PM](https://user-images.githubusercontent.com/6130352/68342478-ae829f80-00b8-11ea-88c6-4c468e4826c9.png)

I think you'll probably get more mileage out of some package or plugin specifically for IMC.  Sorry!

**Comment by mkeays** [comment]
Hi Eric,

Thanks for your quick reply and for explaining -- I will look at some other packages.

Thanks!
Maria
