### ISSUE TITLE
cells at tile edges

### ISSUE THREAD

**Issue by mkeays** [hammerlab/cytokit#17]
Hello,

I am trying to understand more about the Cytokit analysis results now, and was wondering -- since cytometry is done for each tile separately, what happens for the cells that overlap the edges of the tiles, so e.g. half of the cell is in one tile and the other half is in another tile? Are these cells just not counted, or only the part of the cell that contains the nucleus is used, or something else?

Thanks!
Maria

**Comment by eric-czech** [comment]
There is a "[cm|nm]:on_border" flag in the csv/fcs files that indicates whether or not the cell or nucleus (respectively) shares any pixels with the border of the image.  Other than that, the images are segmented as-is and even though the U-Net typically does a good job of identifying nuclei on or near boundaries, I would recommend ignoring them.

**Comment by eric-czech** [comment]
I'll close this out for now, please re-open if you have any more questions on border objects.
