### ISSUE TITLE
Outputting ROI polygon info

### ISSUE THREAD

**Issue by mkeays** [hammerlab/cytokit#25]
Hi @eric-czech ,

I've been asked whether it's possible to get Cytokit to output polygon information for the segmented ROIs i.e. nuclei and cell boundaries. The project I'm working on is converging on OME-TIFF as the preferred format for image data, and we'd like to be able to put this information into OME-XML, if it's possible to pull it out from Cytokit somehow?

Thanks,
Maria

**Comment by eric-czech** [comment]
Hi @mkeays, the images in ```$RESULTS_DIR/cytometry/tile``` contain the label volumes and boundaries for all cells.  In other words, the 5D images in there contain the object images for each cell with an integer label as well as (on a different leading dimension) the boundaries of those same objects.  The "extract" command just pulls images from there and stacks them up with images from ```$RESULTS_DIR/processor/tile``` so you should be able to use them directly.  I don't know how to convert to OME-XML off the top of my head, but I imagine it's pretty straightforward from the labeled images.

**Comment by mkeays** [comment]
Hi @eric-czech , thanks for explaining! I had a feeling the information was already there, I'll look more closely at these images.
