### ISSUE TITLE
Using membrane channel for cell boundary segmentation

### ISSUE THREAD

**Issue by mdayao** [hammerlab/cytokit#26]
Hi @eric-czech,

I am looking to use a membrane stain channel for segmentation the cell boundaries in CODEX data. I see that there is a "processor: cytometry: membrane_channel_name" in the config file for me to specify the membrane channel to use; however, it is unclear to me what the different parameters under "processor: cytometry: segmentation_params" should be set to in this case.

Additionally, I know that Cytokit uses CellProfiler's U-Net for nuclei segmentation, but what is the method of segmentation for the cell membranes?

Thank you,
Monica

**Comment by eric-czech** [comment]
Hi @mdayao, the membrane segmentation is pretty straightforward and is based on CellProfiler methods that made sense in the context of tissue images.  It works like this:

- Apply some gaussian blur; controlled by ```memb_sigma```
- Calculate a threshold; default method is [li](https://scikit-image.org/docs/dev/api/skimage.filters.html#skimage.filters.threshold_li) same as CP but can be changed with ```memb_tresh_method```
- Fill holes in the binary mask from the threshold; controlled by ```memb_hole_size```
- Optionally, clip all membrane pixels to have some minimum or maximum distance from the nearest nucleus pixel; controlled by ```memb_min_dist``` and ```memb_max_dist```
- Segment the cell boundaries using [Voronoi-Based Segmentation of Cells on Image Manifolds](https://link.springer.com/chapter/10.1007/11569541_54); controlled by ```memb_propagation_regularization``` where lower values mean more weight is given to the intensity of the original membrane image and high values mean more emphasis is put on splitting cells at something closer to equidistant points (see [here](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifysecondaryobjects.py#L322) for more details)

I never documented that anywhere but the code for it is [here](https://github.com/hammerlab/cytokit/blob/168c7ebd598664f0833d26078b167456ce4a899d/python/pipeline/cytokit/cytometry/cytometer.py#L937).  This [config](https://github.com/hammerlab/cytokit/blob/168c7ebd598664f0833d26078b167456ce4a899d/pub/config/cell-size/experiment_20x.yaml#L40) also shows some settings I used for membrane segmentation in the publication.

**Comment by mdayao** [comment]
Great, thank you! This is very helpful.
