### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by akashparvatikar** [hammerlab/cytokit#32]
I am trying to run "marker_profiling_example" notebook and while trying to visualize the 6-channel image, I get the following error: 
No such file or directory: '/tmp/cytokit-example/cellular-marker/20181116-d40-r1-20x-5by5/output/v00/montage/best_z_segm/R001.tif'

I think montage folder is missing within v00. Can you please help me with this?

**Comment by eric-czech** [comment]
Hi @AkashParvatikar, were there any errors in the notebook cell output for the cell containing "cytokit processor run_all"?

That is the step that would generate those files.

**Comment by akashparvatikar** [comment]
Hi, you are right. I am getting an error while trying to run the "processor" step cell.

error1: Invalid argument: 'visible_device_list' listed an invalid GPU id '1' but visible device count is 1. distributed.worker - WARNING -  Compute Failed

error2: Exception: Exception('Failed to create session.',)

error3: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

Any thoughts on how to address this?

**Comment by eric-czech** [comment]
You'll have to modify the `gpus` property in the `experiment.yaml` file if you only have one GPU.  That seems most likely given the error.
