### ISSUE TITLE
'int' object has no attribute 'auto_restart'

### ISSUE THREAD

**Issue by akashparvatikar** [hammerlab/cytokit#33]
Hi,
I am trying to run the entire cytokit pipeline on my local machine. While executing "!cytokit processor run_all", I get the following error:

File "/home/akashparvatikar/anaconda3/lib/python3.7/site-packages/cytokit-0.1.1-py3.7.egg/cytokit/exec/pipeline.py", line 406, in run_tasks
 worker.auto_restart = False
AttributeError: 'int' object has no attribute 'auto_restart'

Any idea, what is the issue? Suggestions would be greatly appreciated. Thank you!

**Comment by eric-czech** [comment]
Did you figure out what it was?

**Comment by akashparvatikar** [comment]
Hi,

Firstly, thank you for your response. I am now able to run cytokit successfully.
I had to comment lines 406 and 407 to make it work. Also, I am running cytokit using dask version 2020.12.0
